image: sparkfabrik/spark-k8s-deployer:latest

services:
  - docker:18.09.7-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

before_script:
  - docker login -u oauth2accesstoken -p "$(gcloud auth print-access-token)" https://eu.gcr.io